Update on Vietnamese translation
26F-Studio/Techmino pull request #869
Opened 2023-03-01 00:07 UTC by ShardNguyen

2023-03-04 13:39 UTC, SweetSea-ButImNotSweet commented
![image](https://user-images.githubusercontent.com/106439598/222905533-d4ca5caf-fa92-4f23-8351-f0a5a4abc30f.png)
A small suggestion: translating Field Sway into "Độ nảy bảng" or "Độ lắc bảng"? Sound better

2023-03-05 09:11 UTC, SweetSea-ButImNotSweet requested changes
In short, we need some minor changes

2023-03-05 09:11 UTC, SweetSea-ButImNotSweet commented on parts/language/lang_vi.lua
> +        "Được tạo bằng LÖVE",
(P/s: this part is a bit of messy for me so I spoke in Vietnamese, sorry)
For short, this string I, Shard and some others have discussed at least... 3 times

--------------------------------------------------------------------------------

Anh Sạc, cái này không biết có nên phải **nhắc lại** nữa hay không
(Dù sao em cũng mong đây là lần cuối cùng phải bàn tới cái chuyện này, em nói thật ;-;)

Cái chỗ này em có thêm cái lựa chọn là "Chạy bằng engine LOVE", nhưng đây có khi là **lần thứ 3** bàn tới chuyện này rồi nên nếu mà anh hoang mang thì thử hỏi lại bên cộng đồng TVN thêm một lần nữa xem

2023-03-05 09:11 UTC, SweetSea-ButImNotSweet commented on parts/language/lang_vi.lua
> +            shakeFX="Độ Rung Bảng",
A small suggestion: translating Field Sway into "Độ nảy bảng" or "Độ lắc bảng"? Sound better (or not)


![image](https://user-images.githubusercontent.com/106439598/222905533-d4ca5caf-fa92-4f23-8351-f0a5a4abc30f.png)

2023-03-06 00:32 UTC, ShardNguyen commented
@SweetSea-ButImNotSweet Accepted the 2 changes

2023-03-06 01:41 UTC, SweetSea-ButImNotSweet approved these changes
Ok, @ShardNguyen , I saw your changes

2023-03-27 04:53 UTC, merged